#############################################################################
# Makefile for building: vmrun
# Generated by qmake (3.1) (Qt 5.15.17)
# Project:  vmrun.pro
# Template: app
# Command: /usr/local/bin/qmake-qt5 -o Makefile vmrun.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = clang
CXX           = clang++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -pthread -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++1z -Wall -Wextra -pthread -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/local/include/qt5 -I/usr/local/include/qt5/QtWidgets -I/usr/local/include/qt5/QtGui -I/usr/local/include/qt5/QtCore -I. -I/usr/local/include -I. -I/usr/local/include -I/usr/local/lib/qt5/mkspecs/freebsd-clang
QMAKE         = /usr/local/bin/qmake-qt5
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/local/bin/qmake-qt5 -install qinstall
QINSTALL_PROGRAM = /usr/local/bin/qmake-qt5 -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = vmrun1.0.0
DISTDIR = /home/definitly/vmrun/.tmp/vmrun1.0.0
LINK          = clang++
LFLAGS        = -pthread -Wl,-rpath,/usr/local/lib/qt5
LIBS          = $(SUBLIBS) -L/usr/local/lib /usr/local/lib/qt5/libQt5Widgets.so /usr/local/lib/qt5/libQt5Gui.so /usr/local/lib/qt5/libQt5Core.so -lGL   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp qrc_resources.cpp \
		moc_mainwindow.cpp
OBJECTS       = main.o \
		mainwindow.o \
		qrc_resources.o \
		moc_mainwindow.o
DIST          = /usr/local/lib/qt5/mkspecs/features/spec_pre.prf \
		/usr/local/lib/qt5/mkspecs/common/unix.conf \
		/usr/local/lib/qt5/mkspecs/common/bsd/bsd.conf \
		/usr/local/lib/qt5/mkspecs/common/sanitize.conf \
		/usr/local/lib/qt5/mkspecs/common/gcc-base.conf \
		/usr/local/lib/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/local/lib/qt5/mkspecs/common/clang.conf \
		/usr/local/lib/qt5/mkspecs/qconfig.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_core.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_dbus.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_declarative.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_gui.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_network.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_printsupport.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_widgets.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/lib/qt5/mkspecs/features/qt_functions.prf \
		/usr/local/lib/qt5/mkspecs/features/qt_config.prf \
		/usr/local/lib/qt5/mkspecs/freebsd-clang/qmake.conf \
		/usr/local/lib/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/local/lib/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/local/lib/qt5/mkspecs/features/toolchain.prf \
		/usr/local/lib/qt5/mkspecs/features/default_pre.prf \
		/usr/local/lib/qt5/mkspecs/features/resolve_config.prf \
		/usr/local/lib/qt5/mkspecs/features/default_post.prf \
		/usr/local/lib/qt5/mkspecs/features/warn_on.prf \
		/usr/local/lib/qt5/mkspecs/features/qt.prf \
		/usr/local/lib/qt5/mkspecs/features/resources_functions.prf \
		/usr/local/lib/qt5/mkspecs/features/resources.prf \
		/usr/local/lib/qt5/mkspecs/features/moc.prf \
		/usr/local/lib/qt5/mkspecs/features/unix/opengl.prf \
		/usr/local/lib/qt5/mkspecs/features/uic.prf \
		/usr/local/lib/qt5/mkspecs/features/unix/thread.prf \
		/usr/local/lib/qt5/mkspecs/features/qmake_use.prf \
		/usr/local/lib/qt5/mkspecs/features/file_copies.prf \
		/usr/local/lib/qt5/mkspecs/features/testcase_targets.prf \
		/usr/local/lib/qt5/mkspecs/features/exceptions.prf \
		/usr/local/lib/qt5/mkspecs/features/yacc.prf \
		/usr/local/lib/qt5/mkspecs/features/lex.prf \
		vmrun.pro mainwindow.h main.cpp \
		mainwindow.cpp
QMAKE_TARGET  = vmrun
DESTDIR       = 
TARGET        = vmrun


first: all
####### Build rules

vmrun: ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: vmrun.pro /usr/local/lib/qt5/mkspecs/freebsd-clang/qmake.conf /usr/local/lib/qt5/mkspecs/features/spec_pre.prf \
		/usr/local/lib/qt5/mkspecs/common/unix.conf \
		/usr/local/lib/qt5/mkspecs/common/bsd/bsd.conf \
		/usr/local/lib/qt5/mkspecs/common/sanitize.conf \
		/usr/local/lib/qt5/mkspecs/common/gcc-base.conf \
		/usr/local/lib/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/local/lib/qt5/mkspecs/common/clang.conf \
		/usr/local/lib/qt5/mkspecs/qconfig.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_core.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_dbus.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_declarative.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_gui.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_network.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_printsupport.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_widgets.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/lib/qt5/mkspecs/features/qt_functions.prf \
		/usr/local/lib/qt5/mkspecs/features/qt_config.prf \
		/usr/local/lib/qt5/mkspecs/freebsd-clang/qmake.conf \
		/usr/local/lib/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/local/lib/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/local/lib/qt5/mkspecs/features/toolchain.prf \
		/usr/local/lib/qt5/mkspecs/features/default_pre.prf \
		/usr/local/lib/qt5/mkspecs/features/resolve_config.prf \
		/usr/local/lib/qt5/mkspecs/features/default_post.prf \
		/usr/local/lib/qt5/mkspecs/features/warn_on.prf \
		/usr/local/lib/qt5/mkspecs/features/qt.prf \
		/usr/local/lib/qt5/mkspecs/features/resources_functions.prf \
		/usr/local/lib/qt5/mkspecs/features/resources.prf \
		/usr/local/lib/qt5/mkspecs/features/moc.prf \
		/usr/local/lib/qt5/mkspecs/features/unix/opengl.prf \
		/usr/local/lib/qt5/mkspecs/features/uic.prf \
		/usr/local/lib/qt5/mkspecs/features/unix/thread.prf \
		/usr/local/lib/qt5/mkspecs/features/qmake_use.prf \
		/usr/local/lib/qt5/mkspecs/features/file_copies.prf \
		/usr/local/lib/qt5/mkspecs/features/testcase_targets.prf \
		/usr/local/lib/qt5/mkspecs/features/exceptions.prf \
		/usr/local/lib/qt5/mkspecs/features/yacc.prf \
		/usr/local/lib/qt5/mkspecs/features/lex.prf \
		vmrun.pro \
		resources.qrc
	$(QMAKE) -o Makefile vmrun.pro
/usr/local/lib/qt5/mkspecs/features/spec_pre.prf:
/usr/local/lib/qt5/mkspecs/common/unix.conf:
/usr/local/lib/qt5/mkspecs/common/bsd/bsd.conf:
/usr/local/lib/qt5/mkspecs/common/sanitize.conf:
/usr/local/lib/qt5/mkspecs/common/gcc-base.conf:
/usr/local/lib/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/local/lib/qt5/mkspecs/common/clang.conf:
/usr/local/lib/qt5/mkspecs/qconfig.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_config_core.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_config_dbus.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_config_declarative.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_config_gui.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_config_network.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_config_printsupport.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_config_widgets.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_designer.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_designer_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_help.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_help_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_qml_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_qmlmodels.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_quick_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_quickshapes_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/local/lib/qt5/mkspecs/features/qt_functions.prf:
/usr/local/lib/qt5/mkspecs/features/qt_config.prf:
/usr/local/lib/qt5/mkspecs/freebsd-clang/qmake.conf:
/usr/local/lib/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/local/lib/qt5/mkspecs/features/exclusive_builds.prf:
/usr/local/lib/qt5/mkspecs/features/toolchain.prf:
/usr/local/lib/qt5/mkspecs/features/default_pre.prf:
/usr/local/lib/qt5/mkspecs/features/resolve_config.prf:
/usr/local/lib/qt5/mkspecs/features/default_post.prf:
/usr/local/lib/qt5/mkspecs/features/warn_on.prf:
/usr/local/lib/qt5/mkspecs/features/qt.prf:
/usr/local/lib/qt5/mkspecs/features/resources_functions.prf:
/usr/local/lib/qt5/mkspecs/features/resources.prf:
/usr/local/lib/qt5/mkspecs/features/moc.prf:
/usr/local/lib/qt5/mkspecs/features/unix/opengl.prf:
/usr/local/lib/qt5/mkspecs/features/uic.prf:
/usr/local/lib/qt5/mkspecs/features/unix/thread.prf:
/usr/local/lib/qt5/mkspecs/features/qmake_use.prf:
/usr/local/lib/qt5/mkspecs/features/file_copies.prf:
/usr/local/lib/qt5/mkspecs/features/testcase_targets.prf:
/usr/local/lib/qt5/mkspecs/features/exceptions.prf:
/usr/local/lib/qt5/mkspecs/features/yacc.prf:
/usr/local/lib/qt5/mkspecs/features/lex.prf:
vmrun.pro:
resources.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile vmrun.pro

qmake_all: FORCE


all: Makefile vmrun

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents resources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/local/lib/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: resources.qrc \
		/usr/local/lib/qt5/bin/rcc \
		icons/bhyve.png
	/usr/local/lib/qt5/bin/rcc -name resources resources.qrc -o qrc_resources.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/local/lib/qt5/mkspecs/features/data/dummy.cpp
	clang++ -pipe -O2 -std=gnu++1z -Wall -Wextra -dM -E -o moc_predefs.h /usr/local/lib/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: mainwindow.h \
		/usr/local/include/qt5/QtWidgets/QMainWindow \
		/usr/local/include/qt5/QtWidgets/qmainwindow.h \
		/usr/local/include/qt5/QtWidgets/qtwidgetsglobal.h \
		/usr/local/include/qt5/QtGui/qtguiglobal.h \
		/usr/local/include/qt5/QtCore/qglobal.h \
		/usr/local/include/qt5/QtCore/qconfig-bootstrapped.h \
		/usr/local/include/qt5/QtCore/qconfig.h \
		/usr/local/include/qt5/QtCore/qconfig-modules.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-core.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-dbus.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-declarative.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-gui.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-network.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-printsupport.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-widgets.h \
		/usr/local/include/qt5/QtCore/qtcore-config.h \
		/usr/local/include/qt5/QtCore/qsystemdetection.h \
		/usr/local/include/qt5/QtCore/qprocessordetection.h \
		/usr/local/include/qt5/QtCore/qcompilerdetection.h \
		/usr/local/include/qt5/QtCore/qtypeinfo.h \
		/usr/local/include/qt5/QtCore/qsysinfo.h \
		/usr/local/include/qt5/QtCore/qlogging.h \
		/usr/local/include/qt5/QtCore/qflags.h \
		/usr/local/include/qt5/QtCore/qatomic.h \
		/usr/local/include/qt5/QtCore/qbasicatomic.h \
		/usr/local/include/qt5/QtCore/qatomic_bootstrap.h \
		/usr/local/include/qt5/QtCore/qgenericatomic.h \
		/usr/local/include/qt5/QtCore/qatomic_cxx11.h \
		/usr/local/include/qt5/QtCore/qatomic_msvc.h \
		/usr/local/include/qt5/QtCore/qglobalstatic.h \
		/usr/local/include/qt5/QtCore/qmutex.h \
		/usr/local/include/qt5/QtCore/qtsan_impl.h \
		/usr/local/include/qt5/QtCore/qnumeric.h \
		/usr/local/include/qt5/QtCore/qversiontagging.h \
		/usr/local/include/qt5/QtGui/qtgui-config.h \
		/usr/local/include/qt5/QtWidgets/qtwidgets-config.h \
		/usr/local/include/qt5/QtWidgets/qwidget.h \
		/usr/local/include/qt5/QtGui/qwindowdefs.h \
		/usr/local/include/qt5/QtCore/qobjectdefs.h \
		/usr/local/include/qt5/QtCore/qnamespace.h \
		/usr/local/include/qt5/QtCore/qobjectdefs_impl.h \
		/usr/local/include/qt5/QtGui/qwindowdefs_win.h \
		/usr/local/include/qt5/QtCore/qobject.h \
		/usr/local/include/qt5/QtCore/qstring.h \
		/usr/local/include/qt5/QtCore/qchar.h \
		/usr/local/include/qt5/QtCore/qbytearray.h \
		/usr/local/include/qt5/QtCore/qrefcount.h \
		/usr/local/include/qt5/QtCore/qarraydata.h \
		/usr/local/include/qt5/QtCore/qstringliteral.h \
		/usr/local/include/qt5/QtCore/qstringalgorithms.h \
		/usr/local/include/qt5/QtCore/qstringview.h \
		/usr/local/include/qt5/QtCore/qstringbuilder.h \
		/usr/local/include/qt5/QtCore/qlist.h \
		/usr/local/include/qt5/QtCore/qalgorithms.h \
		/usr/local/include/qt5/QtCore/qiterator.h \
		/usr/local/include/qt5/QtCore/qhashfunctions.h \
		/usr/local/include/qt5/QtCore/qpair.h \
		/usr/local/include/qt5/QtCore/qvector.h \
		/usr/local/include/qt5/QtCore/qcontainertools_impl.h \
		/usr/local/include/qt5/QtCore/qpoint.h \
		/usr/local/include/qt5/QtCore/qbytearraylist.h \
		/usr/local/include/qt5/QtCore/qstringlist.h \
		/usr/local/include/qt5/QtCore/qregexp.h \
		/usr/local/include/qt5/QtCore/qstringmatcher.h \
		/usr/local/include/qt5/QtCore/qcoreevent.h \
		/usr/local/include/qt5/QtCore/qscopedpointer.h \
		/usr/local/include/qt5/QtCore/qmetatype.h \
		/usr/local/include/qt5/QtCore/qvarlengtharray.h \
		/usr/local/include/qt5/QtCore/qcontainerfwd.h \
		/usr/local/include/qt5/QtCore/qobject_impl.h \
		/usr/local/include/qt5/QtCore/qmargins.h \
		/usr/local/include/qt5/QtGui/qpaintdevice.h \
		/usr/local/include/qt5/QtCore/qrect.h \
		/usr/local/include/qt5/QtCore/qsize.h \
		/usr/local/include/qt5/QtGui/qpalette.h \
		/usr/local/include/qt5/QtGui/qcolor.h \
		/usr/local/include/qt5/QtGui/qrgb.h \
		/usr/local/include/qt5/QtGui/qrgba64.h \
		/usr/local/include/qt5/QtGui/qbrush.h \
		/usr/local/include/qt5/QtGui/qmatrix.h \
		/usr/local/include/qt5/QtGui/qpolygon.h \
		/usr/local/include/qt5/QtGui/qregion.h \
		/usr/local/include/qt5/QtCore/qdatastream.h \
		/usr/local/include/qt5/QtCore/qiodevice.h \
		/usr/local/include/qt5/QtCore/qline.h \
		/usr/local/include/qt5/QtGui/qtransform.h \
		/usr/local/include/qt5/QtGui/qimage.h \
		/usr/local/include/qt5/QtGui/qpixelformat.h \
		/usr/local/include/qt5/QtGui/qpixmap.h \
		/usr/local/include/qt5/QtCore/qsharedpointer.h \
		/usr/local/include/qt5/QtCore/qshareddata.h \
		/usr/local/include/qt5/QtCore/qhash.h \
		/usr/local/include/qt5/QtCore/qsharedpointer_impl.h \
		/usr/local/include/qt5/QtGui/qfont.h \
		/usr/local/include/qt5/QtGui/qfontmetrics.h \
		/usr/local/include/qt5/QtGui/qfontinfo.h \
		/usr/local/include/qt5/QtWidgets/qsizepolicy.h \
		/usr/local/include/qt5/QtGui/qcursor.h \
		/usr/local/include/qt5/QtGui/qkeysequence.h \
		/usr/local/include/qt5/QtGui/qevent.h \
		/usr/local/include/qt5/QtCore/qvariant.h \
		/usr/local/include/qt5/QtCore/qmap.h \
		/usr/local/include/qt5/QtCore/qdebug.h \
		/usr/local/include/qt5/QtCore/qtextstream.h \
		/usr/local/include/qt5/QtCore/qlocale.h \
		/usr/local/include/qt5/QtCore/qset.h \
		/usr/local/include/qt5/QtCore/qcontiguouscache.h \
		/usr/local/include/qt5/QtCore/qurl.h \
		/usr/local/include/qt5/QtCore/qurlquery.h \
		/usr/local/include/qt5/QtCore/qfile.h \
		/usr/local/include/qt5/QtCore/qfiledevice.h \
		/usr/local/include/qt5/QtGui/qvector2d.h \
		/usr/local/include/qt5/QtGui/qtouchdevice.h \
		/usr/local/include/qt5/QtWidgets/qtabwidget.h \
		/usr/local/include/qt5/QtGui/qicon.h \
		/usr/local/include/qt5/QtCore/QProcess \
		/usr/local/include/qt5/QtCore/qprocess.h \
		moc_predefs.h \
		/usr/local/lib/qt5/bin/moc
	/usr/local/lib/qt5/bin/moc $(DEFINES) --include /home/definitly/vmrun/moc_predefs.h -I/usr/local/lib/qt5/mkspecs/freebsd-clang -I/home/definitly/vmrun -I/usr/local/include/qt5 -I/usr/local/include/qt5/QtWidgets -I/usr/local/include/qt5/QtGui -I/usr/local/include/qt5/QtCore -I/usr/include/c++/v1 -I/usr/lib/clang/19/include -I/usr/include mainwindow.h -o moc_mainwindow.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui \
		/usr/local/lib/qt5/bin/uic
	/usr/local/lib/qt5/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		/usr/local/include/qt5/QtWidgets/QMainWindow \
		/usr/local/include/qt5/QtWidgets/qmainwindow.h \
		/usr/local/include/qt5/QtWidgets/qtwidgetsglobal.h \
		/usr/local/include/qt5/QtGui/qtguiglobal.h \
		/usr/local/include/qt5/QtCore/qglobal.h \
		/usr/local/include/qt5/QtCore/qconfig-bootstrapped.h \
		/usr/local/include/qt5/QtCore/qconfig.h \
		/usr/local/include/qt5/QtCore/qconfig-modules.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-core.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-dbus.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-declarative.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-gui.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-network.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-printsupport.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-widgets.h \
		/usr/local/include/qt5/QtCore/qtcore-config.h \
		/usr/local/include/qt5/QtCore/qsystemdetection.h \
		/usr/local/include/qt5/QtCore/qprocessordetection.h \
		/usr/local/include/qt5/QtCore/qcompilerdetection.h \
		/usr/local/include/qt5/QtCore/qtypeinfo.h \
		/usr/local/include/qt5/QtCore/qsysinfo.h \
		/usr/local/include/qt5/QtCore/qlogging.h \
		/usr/local/include/qt5/QtCore/qflags.h \
		/usr/local/include/qt5/QtCore/qatomic.h \
		/usr/local/include/qt5/QtCore/qbasicatomic.h \
		/usr/local/include/qt5/QtCore/qatomic_bootstrap.h \
		/usr/local/include/qt5/QtCore/qgenericatomic.h \
		/usr/local/include/qt5/QtCore/qatomic_cxx11.h \
		/usr/local/include/qt5/QtCore/qatomic_msvc.h \
		/usr/local/include/qt5/QtCore/qglobalstatic.h \
		/usr/local/include/qt5/QtCore/qmutex.h \
		/usr/local/include/qt5/QtCore/qtsan_impl.h \
		/usr/local/include/qt5/QtCore/qnumeric.h \
		/usr/local/include/qt5/QtCore/qversiontagging.h \
		/usr/local/include/qt5/QtGui/qtgui-config.h \
		/usr/local/include/qt5/QtWidgets/qtwidgets-config.h \
		/usr/local/include/qt5/QtWidgets/qwidget.h \
		/usr/local/include/qt5/QtGui/qwindowdefs.h \
		/usr/local/include/qt5/QtCore/qobjectdefs.h \
		/usr/local/include/qt5/QtCore/qnamespace.h \
		/usr/local/include/qt5/QtCore/qobjectdefs_impl.h \
		/usr/local/include/qt5/QtGui/qwindowdefs_win.h \
		/usr/local/include/qt5/QtCore/qobject.h \
		/usr/local/include/qt5/QtCore/qstring.h \
		/usr/local/include/qt5/QtCore/qchar.h \
		/usr/local/include/qt5/QtCore/qbytearray.h \
		/usr/local/include/qt5/QtCore/qrefcount.h \
		/usr/local/include/qt5/QtCore/qarraydata.h \
		/usr/local/include/qt5/QtCore/qstringliteral.h \
		/usr/local/include/qt5/QtCore/qstringalgorithms.h \
		/usr/local/include/qt5/QtCore/qstringview.h \
		/usr/local/include/qt5/QtCore/qstringbuilder.h \
		/usr/local/include/qt5/QtCore/qlist.h \
		/usr/local/include/qt5/QtCore/qalgorithms.h \
		/usr/local/include/qt5/QtCore/qiterator.h \
		/usr/local/include/qt5/QtCore/qhashfunctions.h \
		/usr/local/include/qt5/QtCore/qpair.h \
		/usr/local/include/qt5/QtCore/qvector.h \
		/usr/local/include/qt5/QtCore/qcontainertools_impl.h \
		/usr/local/include/qt5/QtCore/qpoint.h \
		/usr/local/include/qt5/QtCore/qbytearraylist.h \
		/usr/local/include/qt5/QtCore/qstringlist.h \
		/usr/local/include/qt5/QtCore/qregexp.h \
		/usr/local/include/qt5/QtCore/qstringmatcher.h \
		/usr/local/include/qt5/QtCore/qcoreevent.h \
		/usr/local/include/qt5/QtCore/qscopedpointer.h \
		/usr/local/include/qt5/QtCore/qmetatype.h \
		/usr/local/include/qt5/QtCore/qvarlengtharray.h \
		/usr/local/include/qt5/QtCore/qcontainerfwd.h \
		/usr/local/include/qt5/QtCore/qobject_impl.h \
		/usr/local/include/qt5/QtCore/qmargins.h \
		/usr/local/include/qt5/QtGui/qpaintdevice.h \
		/usr/local/include/qt5/QtCore/qrect.h \
		/usr/local/include/qt5/QtCore/qsize.h \
		/usr/local/include/qt5/QtGui/qpalette.h \
		/usr/local/include/qt5/QtGui/qcolor.h \
		/usr/local/include/qt5/QtGui/qrgb.h \
		/usr/local/include/qt5/QtGui/qrgba64.h \
		/usr/local/include/qt5/QtGui/qbrush.h \
		/usr/local/include/qt5/QtGui/qmatrix.h \
		/usr/local/include/qt5/QtGui/qpolygon.h \
		/usr/local/include/qt5/QtGui/qregion.h \
		/usr/local/include/qt5/QtCore/qdatastream.h \
		/usr/local/include/qt5/QtCore/qiodevice.h \
		/usr/local/include/qt5/QtCore/qline.h \
		/usr/local/include/qt5/QtGui/qtransform.h \
		/usr/local/include/qt5/QtGui/qimage.h \
		/usr/local/include/qt5/QtGui/qpixelformat.h \
		/usr/local/include/qt5/QtGui/qpixmap.h \
		/usr/local/include/qt5/QtCore/qsharedpointer.h \
		/usr/local/include/qt5/QtCore/qshareddata.h \
		/usr/local/include/qt5/QtCore/qhash.h \
		/usr/local/include/qt5/QtCore/qsharedpointer_impl.h \
		/usr/local/include/qt5/QtGui/qfont.h \
		/usr/local/include/qt5/QtGui/qfontmetrics.h \
		/usr/local/include/qt5/QtGui/qfontinfo.h \
		/usr/local/include/qt5/QtWidgets/qsizepolicy.h \
		/usr/local/include/qt5/QtGui/qcursor.h \
		/usr/local/include/qt5/QtGui/qkeysequence.h \
		/usr/local/include/qt5/QtGui/qevent.h \
		/usr/local/include/qt5/QtCore/qvariant.h \
		/usr/local/include/qt5/QtCore/qmap.h \
		/usr/local/include/qt5/QtCore/qdebug.h \
		/usr/local/include/qt5/QtCore/qtextstream.h \
		/usr/local/include/qt5/QtCore/qlocale.h \
		/usr/local/include/qt5/QtCore/qset.h \
		/usr/local/include/qt5/QtCore/qcontiguouscache.h \
		/usr/local/include/qt5/QtCore/qurl.h \
		/usr/local/include/qt5/QtCore/qurlquery.h \
		/usr/local/include/qt5/QtCore/qfile.h \
		/usr/local/include/qt5/QtCore/qfiledevice.h \
		/usr/local/include/qt5/QtGui/qvector2d.h \
		/usr/local/include/qt5/QtGui/qtouchdevice.h \
		/usr/local/include/qt5/QtWidgets/qtabwidget.h \
		/usr/local/include/qt5/QtGui/qicon.h \
		/usr/local/include/qt5/QtCore/QProcess \
		/usr/local/include/qt5/QtCore/qprocess.h \
		/usr/local/include/qt5/QtWidgets/QApplication \
		/usr/local/include/qt5/QtWidgets/qapplication.h \
		/usr/local/include/qt5/QtCore/qcoreapplication.h \
		/usr/local/include/qt5/QtCore/qeventloop.h \
		/usr/local/include/qt5/QtWidgets/qdesktopwidget.h \
		/usr/local/include/qt5/QtGui/qguiapplication.h \
		/usr/local/include/qt5/QtGui/qinputmethod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		/usr/local/include/qt5/QtWidgets/QMainWindow \
		/usr/local/include/qt5/QtWidgets/qmainwindow.h \
		/usr/local/include/qt5/QtWidgets/qtwidgetsglobal.h \
		/usr/local/include/qt5/QtGui/qtguiglobal.h \
		/usr/local/include/qt5/QtCore/qglobal.h \
		/usr/local/include/qt5/QtCore/qconfig-bootstrapped.h \
		/usr/local/include/qt5/QtCore/qconfig.h \
		/usr/local/include/qt5/QtCore/qconfig-modules.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-core.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-dbus.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-declarative.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-gui.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-network.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-printsupport.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-widgets.h \
		/usr/local/include/qt5/QtCore/qtcore-config.h \
		/usr/local/include/qt5/QtCore/qsystemdetection.h \
		/usr/local/include/qt5/QtCore/qprocessordetection.h \
		/usr/local/include/qt5/QtCore/qcompilerdetection.h \
		/usr/local/include/qt5/QtCore/qtypeinfo.h \
		/usr/local/include/qt5/QtCore/qsysinfo.h \
		/usr/local/include/qt5/QtCore/qlogging.h \
		/usr/local/include/qt5/QtCore/qflags.h \
		/usr/local/include/qt5/QtCore/qatomic.h \
		/usr/local/include/qt5/QtCore/qbasicatomic.h \
		/usr/local/include/qt5/QtCore/qatomic_bootstrap.h \
		/usr/local/include/qt5/QtCore/qgenericatomic.h \
		/usr/local/include/qt5/QtCore/qatomic_cxx11.h \
		/usr/local/include/qt5/QtCore/qatomic_msvc.h \
		/usr/local/include/qt5/QtCore/qglobalstatic.h \
		/usr/local/include/qt5/QtCore/qmutex.h \
		/usr/local/include/qt5/QtCore/qtsan_impl.h \
		/usr/local/include/qt5/QtCore/qnumeric.h \
		/usr/local/include/qt5/QtCore/qversiontagging.h \
		/usr/local/include/qt5/QtGui/qtgui-config.h \
		/usr/local/include/qt5/QtWidgets/qtwidgets-config.h \
		/usr/local/include/qt5/QtWidgets/qwidget.h \
		/usr/local/include/qt5/QtGui/qwindowdefs.h \
		/usr/local/include/qt5/QtCore/qobjectdefs.h \
		/usr/local/include/qt5/QtCore/qnamespace.h \
		/usr/local/include/qt5/QtCore/qobjectdefs_impl.h \
		/usr/local/include/qt5/QtGui/qwindowdefs_win.h \
		/usr/local/include/qt5/QtCore/qobject.h \
		/usr/local/include/qt5/QtCore/qstring.h \
		/usr/local/include/qt5/QtCore/qchar.h \
		/usr/local/include/qt5/QtCore/qbytearray.h \
		/usr/local/include/qt5/QtCore/qrefcount.h \
		/usr/local/include/qt5/QtCore/qarraydata.h \
		/usr/local/include/qt5/QtCore/qstringliteral.h \
		/usr/local/include/qt5/QtCore/qstringalgorithms.h \
		/usr/local/include/qt5/QtCore/qstringview.h \
		/usr/local/include/qt5/QtCore/qstringbuilder.h \
		/usr/local/include/qt5/QtCore/qlist.h \
		/usr/local/include/qt5/QtCore/qalgorithms.h \
		/usr/local/include/qt5/QtCore/qiterator.h \
		/usr/local/include/qt5/QtCore/qhashfunctions.h \
		/usr/local/include/qt5/QtCore/qpair.h \
		/usr/local/include/qt5/QtCore/qvector.h \
		/usr/local/include/qt5/QtCore/qcontainertools_impl.h \
		/usr/local/include/qt5/QtCore/qpoint.h \
		/usr/local/include/qt5/QtCore/qbytearraylist.h \
		/usr/local/include/qt5/QtCore/qstringlist.h \
		/usr/local/include/qt5/QtCore/qregexp.h \
		/usr/local/include/qt5/QtCore/qstringmatcher.h \
		/usr/local/include/qt5/QtCore/qcoreevent.h \
		/usr/local/include/qt5/QtCore/qscopedpointer.h \
		/usr/local/include/qt5/QtCore/qmetatype.h \
		/usr/local/include/qt5/QtCore/qvarlengtharray.h \
		/usr/local/include/qt5/QtCore/qcontainerfwd.h \
		/usr/local/include/qt5/QtCore/qobject_impl.h \
		/usr/local/include/qt5/QtCore/qmargins.h \
		/usr/local/include/qt5/QtGui/qpaintdevice.h \
		/usr/local/include/qt5/QtCore/qrect.h \
		/usr/local/include/qt5/QtCore/qsize.h \
		/usr/local/include/qt5/QtGui/qpalette.h \
		/usr/local/include/qt5/QtGui/qcolor.h \
		/usr/local/include/qt5/QtGui/qrgb.h \
		/usr/local/include/qt5/QtGui/qrgba64.h \
		/usr/local/include/qt5/QtGui/qbrush.h \
		/usr/local/include/qt5/QtGui/qmatrix.h \
		/usr/local/include/qt5/QtGui/qpolygon.h \
		/usr/local/include/qt5/QtGui/qregion.h \
		/usr/local/include/qt5/QtCore/qdatastream.h \
		/usr/local/include/qt5/QtCore/qiodevice.h \
		/usr/local/include/qt5/QtCore/qline.h \
		/usr/local/include/qt5/QtGui/qtransform.h \
		/usr/local/include/qt5/QtGui/qimage.h \
		/usr/local/include/qt5/QtGui/qpixelformat.h \
		/usr/local/include/qt5/QtGui/qpixmap.h \
		/usr/local/include/qt5/QtCore/qsharedpointer.h \
		/usr/local/include/qt5/QtCore/qshareddata.h \
		/usr/local/include/qt5/QtCore/qhash.h \
		/usr/local/include/qt5/QtCore/qsharedpointer_impl.h \
		/usr/local/include/qt5/QtGui/qfont.h \
		/usr/local/include/qt5/QtGui/qfontmetrics.h \
		/usr/local/include/qt5/QtGui/qfontinfo.h \
		/usr/local/include/qt5/QtWidgets/qsizepolicy.h \
		/usr/local/include/qt5/QtGui/qcursor.h \
		/usr/local/include/qt5/QtGui/qkeysequence.h \
		/usr/local/include/qt5/QtGui/qevent.h \
		/usr/local/include/qt5/QtCore/qvariant.h \
		/usr/local/include/qt5/QtCore/qmap.h \
		/usr/local/include/qt5/QtCore/qdebug.h \
		/usr/local/include/qt5/QtCore/qtextstream.h \
		/usr/local/include/qt5/QtCore/qlocale.h \
		/usr/local/include/qt5/QtCore/qset.h \
		/usr/local/include/qt5/QtCore/qcontiguouscache.h \
		/usr/local/include/qt5/QtCore/qurl.h \
		/usr/local/include/qt5/QtCore/qurlquery.h \
		/usr/local/include/qt5/QtCore/qfile.h \
		/usr/local/include/qt5/QtCore/qfiledevice.h \
		/usr/local/include/qt5/QtGui/qvector2d.h \
		/usr/local/include/qt5/QtGui/qtouchdevice.h \
		/usr/local/include/qt5/QtWidgets/qtabwidget.h \
		/usr/local/include/qt5/QtGui/qicon.h \
		/usr/local/include/qt5/QtCore/QProcess \
		/usr/local/include/qt5/QtCore/qprocess.h \
		ui_mainwindow.h \
		/usr/local/include/qt5/QtWidgets/QMessageBox \
		/usr/local/include/qt5/QtWidgets/qmessagebox.h \
		/usr/local/include/qt5/QtWidgets/qdialog.h \
		/usr/local/include/qt5/QtCore/QTimer \
		/usr/local/include/qt5/QtCore/qtimer.h \
		/usr/local/include/qt5/QtCore/qbasictimer.h \
		/usr/local/include/qt5/QtCore/QDebug \
		/usr/local/include/qt5/QtCore/QFileInfo \
		/usr/local/include/qt5/QtCore/qfileinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/vmrun/bin || mkdir -p $(INSTALL_ROOT)/opt/vmrun/bin
	$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/vmrun/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/opt/vmrun/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/vmrun/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/vmrun/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

